# Generated by Django 4.2.6 on 2024-05-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_flashgames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashgames',
            options={'verbose_name': 'Флэш игра', 'verbose_name_plural': 'Флэш игры'},
        ),
        migrations.AddField(
            model_name='flashgames',
            name='height',
            field=models.PositiveIntegerField(default=480),
        ),
        migrations.AddField(
            model_name='flashgames',
            name='width',
            field=models.PositiveIntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='flashgames',
            name='file',
            field=models.FileField(upload_to='games/', verbose_name='Загружить файл(SWF)'),
        ),
        migrations.AlterField(
            model_name='flashgames',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
